apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mailman.fullname" . }}-frontend
  labels:
    {{- include "mailman.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  {{- if not .Values.mailman.frontend.autoscaling.enabled }}
  replicas: {{ .Values.mailman.frontend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mailman.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.mailman.frontend.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "mailman.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mailman.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.mailman.frontend.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          securityContext:
            {{- toYaml .Values.mailman.frontend.securityContext | nindent 12 }}
          image: "{{ .Values.mailman.frontend.image.registry }}/{{ .Values.mailman.frontend.image.repository }}:{{ .Values.mailman.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.mailman.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
            {{- toYaml .Values.mailman.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: http
            {{- toYaml .Values.mailman.frontend.readinessProbe | nindent 12 }}
          env:
            {{- if .Values.configMaps.app.create }}
            - name: FRONTEND_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configMaps.app.name }}
                  key: FRONTEND_URL
            {{- end }}
            {{- range $key, $val := .Values.mailman.frontend.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.mailman.frontend.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /var/cache/nginx
            - name: run
              mountPath: /var/run
      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
        - name: run
          emptyDir: {}
      {{- with .Values.mailman.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mailman.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mailman.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}